<?php

namespace RRZE\Legal;

defined('ABSPATH') || exit;

$settings = [
    'version' => 1,
    'options_page' => [
        'parent' => [
            'slug' => 'legal',
        ],
        'page' => [
            'title' => __('Consent Cookies', 'rrze-legal'),
        ],
        'menu' => [
            'title' => __('Consent Cookies', 'rrze-legal'),
            'capability' => 'manage_options',
            'slug' => 'consent-cookies',
            'position' => 20,
        ],
    ],
    'settings' => [
        'title' => __('Consent Cookies', 'rrze-legal'),
        'sections' => [
            [
                'id' => 'consent_cookies',
                'title' => apply_filters('rrze_legal_section_consent_edit_new_title', __('Add New Cookie', 'rrze-legal')),
                'description' => '',
                'subsections' => [
                    [
                        'id' => 'general',
                        'title' => '',
                        'hide_title' => true,
                        'callback' => [consentCookies(), 'pluginDependencyEditNotice'],
                        'fields' => [
                            [
                                'name' => 'status',
                                'label' => __('Status', 'rrze-legal'),
                                'description' => __('The status of this <strong>Cookie</strong>. If enabled (Status: Enabled) it is displayed to the visitor in the <strong>Consent Banner</strong>', 'rrze-legal'),
                                'type' => 'checkbox',
                                'default' => '0',
                                'hide_when_plugin_slug' => true,
                            ],
                            [
                                'name' => 'position',
                                'label' => __('Position', 'rrze-legal'),
                                'description' => __('Order in the privacy policy', 'rrze-legal'),
                                'placeholder' => '1',
                                'min' => '1',
                                'max' => '99',
                                'step' => '1',
                                'type' => 'number',
                                'default' => '1',
                                'sanitize_callback' => [consentCookies(), 'sanitizePosition'],
                            ],
                        ],
                    ],
                    [
                        'id' => 'privacy',
                        'title' => __('Privacy Information', 'rrze-legal'),
                        'description' => '',
                        'fields' => [
                            [
                                'name' => 'category',
                                'label' => __('Category', 'rrze-legal'),
                                'description' => __('The <strong>Consent Category</strong> the <strong>Cookie</strong> is part of.', 'rrze-legal'),
                                'type' => 'select',
                                'options' => consentCategories()->getItemsOptions(),
                                'default' => 'external_media',
                            ],
                            [
                                'name' => 'name',
                                'label' => __('Name', 'rrze-legal'),
                                'description' => __('Insert a name for this <strong>Cookie</strong>.', 'rrze-legal'),
                                'type' => 'text',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_text_field',
                                'required' => true,
                            ],
                            [
                                'name' => 'provider',
                                'label' => __('Provider', 'rrze-legal'),
                                'description' => __('Insert the provider of this <strong>Cookie</strong>.', 'rrze-legal'),
                                'type' => 'text',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_text_field',
                                'required' => true,
                            ],
                            [
                                'name' => 'purpose',
                                'label' => __('Purpose', 'rrze-legal'),
                                'description' => __('Explain the purpose of this <strong>Cookie</strong> to the visitors.', 'rrze-legal'),
                                'type' => 'textarea',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_textarea_field',
                                'required' => true,
                            ],
                            [
                                'name' => 'privacy_text_de',
                                'label' => __('Privacy Policy Text (DE)', 'rrze-legal'),
                                'description' => __('Plain text without HTML. Blank lines are automatically rendered as paragraphs.', 'rrze-legal'),
                                'type' => 'textarea',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_textarea_field',
                            ],
                            [
                                'name' => 'privacy_text_en',
                                'label' => __('Privacy Policy Text (EN)', 'rrze-legal'),
                                'description' => __('Plain text without HTML. Blank lines are automatically rendered as paragraphs.', 'rrze-legal'),
                                'type' => 'textarea',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_textarea_field',
                            ],
                            [
                                'name' => 'privacy_policy_url',
                                'label' => __('Privacy Policy URL', 'rrze-legal'),
                                'description' => __('Provide a URL to the privacy policy of the provider of the <strong>Cookie</strong>.', 'rrze-legal'),
                                'type' => 'text',
                                'placeholder' => 'https://',
                                'sanitize_callback' => 'sanitize_url',
                                'required' => true,
                            ],
                        ],
                    ],
                    [
                        'id' => 'technical',
                        'title' => __('Technical Information (Advanced Settings)', 'rrze-legal'),
                        'callback' => [consentCookies(), 'technicalSectionToggle'],
                        'fields' => [
                            [
                                'name' => 'id',
                                'label' => __('ID', 'rrze-legal'),
                                'description' => __('The <strong>ID</strong> must be at least 3 characters long and may only contain <code>a-z_-</code> characters.', 'rrze-legal'),
                                'type' => 'text',
                                'default' => '',
                                'size' => 'normal',
                                'disabled' => false,
                                'sanitize_callback' => [consentCookies(), 'sanitizeId'],
                                'required' => true,
                            ],
                            [
                                'name' => 'hosts',
                                'label' => __('Host(s)', 'rrze-legal'),
                                'description' => __('Insert the host(s) of this <strong>Cookie</strong>.', 'rrze-legal'),
                                'type' => 'textarea',
                                'default' => '',
                                'sanitize_callback' => [consentCookies(), 'sanitizeTextareaList'],
                            ],
                            [
                                'name' => 'cookie_name',
                                'label' => __('Cookie Name', 'rrze-legal'),
                                'description' => __('Provide the technical name of the <strong>Cookie</strong>. Separate multiple cookie names with a comma.', 'rrze-legal'),
                                'type' => 'text',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_text_field',
                            ],
                            [
                                'name' => 'cookie_expiry',
                                'label' => __('Cookie Expiry', 'rrze-legal'),
                                'description' => __('Provide the expiry date of the <strong>Cookie</strong>.', 'rrze-legal'),
                                'type' => 'text',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_text_field',
                                'required' => true,
                            ],
                            [
                                'name' => 'plugin_slug',
                                'label' => __('Plugin-Slug', 'rrze-legal'),
                                'description' => __('Optional. If a plugin slug is provided, the status is automatically derived from the activation of this plugin and cannot be set manually.', 'rrze-legal'),
                                'type' => 'text',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_text_field',
                                'capability' => consentCookies()->restrictedTechnicalFieldsCapability(),
                            ],
                            [
                                'name' => 'enqueued_script_handles',
                                'label' => __('Enqueued Script Name', 'rrze-legal'),
                                'description' => __('Name of the enqueued script. It is required if you want to block the script. Separate multiple names with a comma.', 'rrze-legal'),
                                'type' => 'text',
                                'default' => '',
                                'sanitize_callback' => 'sanitize_text_field',
                                'capability' => consentCookies()->restrictedTechnicalFieldsCapability(),
                            ],
                            [
                                'name' => 'block_enqueued_script',
                                'label' => __('Block Enqueued Script', 'rrze-legal'),
                                'description' => __('The enqueued script will be blocked', 'rrze-legal'),
                                'type' => 'checkbox',
                                'default' => '0',
                                'capability' => consentCookies()->restrictedTechnicalFieldsCapability(),
                            ],
                            [
                                'name' => 'prioritize',
                                'label' => __('Prioritize Opt-in Code', 'rrze-legal'),
                                'description' => __('The <strong>Opt-in Code</strong> is loaded in <head> and is executed before the page is fully loaded', 'rrze-legal'),
                                'type' => 'checkbox',
                                'default' => '0',
                                'capability' => consentCookies()->restrictedTechnicalFieldsCapability(),
                            ],
                            [
                                'name' => 'async_opt_out_code',
                                'label' => __('Asynchronous Opt-Out Code', 'rrze-legal'),
                                'description' => __('The <strong>Opt-Out Code</strong> contains asynchronous JavaScript code that needs to executed to finish the Opt-Out', 'rrze-legal'),
                                'type' => 'checkbox',
                                'default' => '0',
                                'capability' => consentCookies()->restrictedTechnicalFieldsCapability(),
                            ],
                            [
                                'name' => 'opt_in_js',
                                'label' => __('Opt-in Code', 'rrze-legal'),
                                'description' => __('This code will be executed after the visitor gives their consent.', 'rrze-legal'),
                                'type' => 'htmleditor',
                                'default' => '',
                                'sanitize_callback' => 'stripslashes',
                                'capability' => consentCookies()->restrictedTechnicalFieldsCapability(),
                            ],
                            [
                                'name' => 'opt_out_js',
                                'label' => __('Opt-out Code', 'rrze-legal'),
                                'description' => __('This code will be executed only if the visitor did opt-in previously and chooses to opt-out. It is executed once.', 'rrze-legal'),
                                'type' => 'htmleditor',
                                'default' => '',
                                'sanitize_callback' => 'stripslashes',
                                'capability' => consentCookies()->restrictedTechnicalFieldsCapability(),
                            ],
                            [
                                'name' => 'fallback_js',
                                'label' => __('Fallback Code', 'rrze-legal'),
                                'description' => __('This code will always be executed.', 'rrze-legal'),
                                'type' => 'htmleditor',
                                'default' => '',
                                'sanitize_callback' => 'stripslashes',
                                'capability' => consentCookies()->restrictedTechnicalFieldsCapability(),
                            ],
                        ],
                    ],
                ],
            ],
        ]
    ],
];
